=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/34/1OMAS01.dtd
<!ELEMENT SUPER-ELEMENTO ((ELEMENTO+))>
<!ELEMENT SUB-ELEMENTO (#PCDATA)>
<!ELEMENT MEGA-ELEMENTO ((SUPER-ELEMENTO+))>
<!ELEMENT ELEMENTO (#PCDATA | SUB-ELEMENTO)*>

=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/34/1OMAS01.xml
<!DOCTYPE MEGA-ELEMENTO SYSTEM "1OMAS01.dtd">
<MEGA-ELEMENTO>
	<SUPER-ELEMENTO>
		<ELEMENTO>
			<SUB-ELEMENTO>
			
			</SUB-ELEMENTO>
		</ELEMENTO>
		<ELEMENTO>
		
		</ELEMENTO>
	</SUPER-ELEMENTO>
	<SUPER-ELEMENTO>
		<ELEMENTO>
			<SUB-ELEMENTO>
			
			</SUB-ELEMENTO>
		</ELEMENTO>
	</SUPER-ELEMENTO>
</MEGA-ELEMENTO>
