=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/37/ATTLIST.dtd
<!ELEMENT USUARIOS ((USUARIO+))>
<!ELEMENT USUARIO ((NOMBRE, EDAD, NICK, PASSWORD))>
<!ATTLIST USUARIO
	id (003 | 002 | 001) #REQUIRED
	tipo (PROFESOR | ALUMNO | ADMINISTRADOR) #REQUIRED
>
<!ELEMENT PASSWORD (#PCDATA)>
<!ELEMENT NOMBRE (#PCDATA)>
<!ELEMENT NICK (#PCDATA)>
<!ELEMENT EDAD (#PCDATA)>

=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/37/ATTLIST.xml
<!DOCTYPE USUARIOS SYSTEM "ATTLIST.dtd">
<USUARIOS>
	<USUARIO id="001" tipo="ALUMNO">
		<NOMBRE>Efra</NOMBRE>
		<EDAD>20</EDAD>
		<NICK>eefra1997</NICK>
		<PASSWORD>123456</PASSWORD>
	</USUARIO>
	<USUARIO id="002" tipo="ADMINISTRADOR">
		<NOMBRE>Kai</NOMBRE>
		<EDAD>21</EDAD>
		<NICK>jkaimorts</NICK>
		<PASSWORD>789012</PASSWORD>
	</USUARIO>
	<USUARIO id="003" tipo="PROFESOR">
		<NOMBRE>Beto</NOMBRE>
		<EDAD>20</EDAD>
		<NICK>albertoEsq</NICK>
		<PASSWORD>345678</PASSWORD>
	</USUARIO>
</USUARIOS>
