=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/33/DTDAny02.dtd
<!ELEMENT SUB-ELEMENTO (#PCDATA | A | B | C)*>
<!ELEMENT PRINCIPAL ((ELEMENTO+))>
<!ELEMENT ELEMENTO (#PCDATA | SUB-ELEMENTO)*>
<!ELEMENT C ANY>
<!ELEMENT B ANY>
<!ELEMENT A ANY>

=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/33/ANY02.xml
<!DOCTYPE PRINCIPAL SYSTEM "DTDAny02.dtd">
<PRINCIPAL>
	<ELEMENTO>
		<SUB-ELEMENTO>
			<A/>
			<B/>
			<C/>
		</SUB-ELEMENTO>
	</ELEMENTO>
	<ELEMENTO>
		<SUB-ELEMENTO>
			<A/>
			<B/>
		</SUB-ELEMENTO>
	</ELEMENTO>
	<ELEMENTO>
		<SUB-ELEMENTO>		
		</SUB-ELEMENTO>
	</ELEMENTO>
	<ELEMENTO>
	</ELEMENTO>
</PRINCIPAL>
