=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/33/MIXED02.dtd
<!ELEMENT super-elemento ((elemento01, elemento02, elemento03))>
<!ELEMENT sub-elemento (#PCDATA | a)*>
<!ELEMENT elemento03 ((sub-elemento))>
<!ELEMENT elemento02 ((sub-elemento))>
<!ELEMENT elemento01 ((sub-elemento))>
<!ELEMENT a EMPTY>

=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/33/MIXED02.xml
<!DOCTYPE super-elemento SYSTEM "MIXED02.dtd">
<super-elemento>
	<elemento01>
		<sub-elemento>
		
		</sub-elemento>
	</elemento01>
	<elemento02>
		<sub-elemento>
			texto sub elemento
		</sub-elemento>
	</elemento02>
	<elemento03>
		<sub-elemento>
			<a/>
		</sub-elemento>
	</elemento03>
</super-elemento>
