=== ErikMC10/ESCOM/Tecnologías para la web/Exposición/MapsJavaScriptApi/web/Markers.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="MARKERS">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="MARKER" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="TITLE" type="xs:string"/>
							<xs:element name="LATITUDE" type="xs:double"/>
							<xs:element name="LONGITUDE" type="xs:double"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ErikMC10/ESCOM/Tecnologías para la web/Exposición/MapsJavaScriptApi/web/Markers.xml
<MARKERS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Markers.xsd">
	<MARKER>
		<TITLE>ESCOM</TITLE>
		<LATITUDE>19.5045672</LATITUDE>
		<LONGITUDE>-99.1490985</LONGITUDE>
	</MARKER>
	<MARKER>
		<TITLE>CHINA</TITLE>
		<LATITUDE>34.4153555</LATITUDE>
		<LONGITUDE>86.0557319</LONGITUDE>
	</MARKER>
	<MARKER>
		<TITLE>ESPANIA</TITLE>
		<LATITUDE>40.1216937</LATITUDE>
		<LONGITUDE>-8.2030557</LONGITUDE>
	</MARKER>
	<MARKER>
		<TITLE>LASVEGAS</TITLE>
		<LATITUDE>36.1249185</LATITUDE>
		<LONGITUDE>-115.3150847</LONGITUDE>
	</MARKER>
</MARKERS>
