=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/36/IMPLIED.dtd
<!ELEMENT ETIQUETOTA ((ETIQUETA+))>
<!ELEMENT ETIQUETITA (#PCDATA)>
<!ELEMENT ETIQUETA ((ETIQUETITA+))>
<!ATTLIST ETIQUETA
	numero_etiquetitas (2 | 1) #IMPLIED
>

=== ErikMC10/ESCOM/Tecnologías para la web/CD/CD FINAL/36/IMPLIED.xml
<!DOCTYPE ETIQUETOTA SYSTEM "IMPLIED.dtd">
<ETIQUETOTA>
	<ETIQUETA numero_etiquetitas="1">
		<ETIQUETITA>
		
		</ETIQUETITA>
	</ETIQUETA>
	<ETIQUETA numero_etiquetitas="2">
		<ETIQUETITA>
		
		</ETIQUETITA>
		<ETIQUETITA>
		
		</ETIQUETITA>
	</ETIQUETA>
	
	<ETIQUETA>
		<ETIQUETITA></ETIQUETITA>
	</ETIQUETA>
</ETIQUETOTA>
